services:
  db:
    image: postgres
    container_name: postgres-container
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_USER=$PL_DATA_POSTGRES_USER
      - POSTGRES_DB=$PL_DATA_POSTGRES_DATABASE
      - POSTGRES_PASSWORD=$PL_DATA_POSTGRES_PASSWORD
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default
        # ipv4_address: 172.20.128.10
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    user: "5050:5050"
    depends_on:
      - db
    networks:
      - default
        # ipv4_address: 172.20.128.11

volumes:
    pg-data:
    pgadmin-data:
networks:
  default:
    name: writeonce-network
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/16
    #       gateway: 172.20.0.1
